site_name: GenJAXMix

theme:
  name: "material"
  # features:
  #   - navigation.tabs
  #   - toc.follow
  #   - toc.integrate

# markdown_extensions:
#   - toc

plugins:
  - mkdocs-jupyter:
      execute: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false


nav: 
  - Home: index.md
  - Tutorials: 
    - Getting Started: tutorials/test.py
  - Library Reference: 
    - API: reference/api.md
    - Conjugacy: reference/conjugacy.md
    - Inference: reference/inference.md
  - For Developers: dev.md