name: Ruff linter

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11" 
    - uses: astral-sh/ruff-action@v3
      with:
        src: "./genjaxmix"
    - run: ruff check --fix
    - run: ruff format

